version: "2"
services:
  # blog 管理端
  blog-element:
    image: nginx
    container_name: blog-element-admin
    networks:
      - blog-net
    ports:
      - 8080:8080
    restart: always
    privileged: true
    # 映射目录
    volumes:
      # 首页文件
      - ./blog-element-admin/dist:/usr/share/nginx/html
      # 配置文件
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # 日志文件
      - ./nginx/log:/var/log/nginx
networks:
  blog-net:
    driver: bridge